version: '2'
services:
    test2-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/Test2/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=Test2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
